[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
merkle_distributor = "9xXVvfr2XEikR7ZFScHtNY2Gb4s5jKTLXNTnTtux99KD"

[[test.genesis]]
address = "Ej1dzP3RQNCduML7agURSUxVKWz3xXJ9wpyKC149m44Y"
program = "./deps/zeta-staking/target/deploy/zeta_staking.so"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000"

