[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
merkle_distributor = "5Ypn3sGFXCpQT7xptYezfF3hgXak59PQHZBoSsch4Sbb"

[[test.genesis]]
address = "8bk6VdmdDnfrq5DeZz8gBzAgffEoc7C51SqXJnxmuSFV"
program = "./deps/zeta-staking/target/deploy/zeta_staking.so"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000"

